import './globals.css'
import { Inter } from 'next/font/google'
import {GlobalContextProvider} from "./context/GlobalProvider";
import Navbar from './component/navbar';
import Footer from './component/footer';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen flex-col items-center justify-between p-24`}>
      <GlobalContextProvider> 
        <Navbar/>
      {children}
      </GlobalContextProvider>
        <Footer/>
      </body>
    </html>
  )
}
